default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mysql

development:
  <<: *default
  database: travel_agency_backend_development
  username: root
  password: password 

test:
  <<: *default
  database: travel_agency_backend_test
  username: root
  password: password

production:
  <<: *default
  database: travel_agency_backend_production
  username: travel_agency_backend
  password: <%= ENV["DATABASE_PASSWORD"] %>